apiVersion: 1
groups:
    - orgId: 1
      name: eval_1m
      folder: distrans
      interval: 1m
      rules:
        - uid: cd3b6ce2-a507-4add-aa86-e36aeb9baa3e
          title: distrans-pods-mem-high-85
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: P67922E13F14564F3
              model:
                datasource: "Promethues_Distrans_Datasource"
                editorMode: code
                expr: round(max by (pod)(max_over_time(container_memory_usage_bytes{namespace="${namespace}"}[1m]))/ on (pod) (kube_pod_container_resource_limits{namespace="${namespace}", resource="memory"}) * 100, 0.01)
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: B
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 85
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          isPaused: false
