{
 "title": "Distrans",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "pod", "label": "Pod", "query": { "query": "label_values(pod)" } },
   { "name": "namespace", "label": "Namespace", "query": "distrans" }
  ]
 },
 "panels": [
  { "title": "WIndows Server Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU % Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (100 * sum by (instance) (irate(windows_cpu_time_total{job=\"supercheap_app_windows_server\", mode=\"idle\"}[1m]))/sum by (instance) (irate(windows_cpu_time_total{job=\"supercheap_app_windows_server\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory % Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(100 - (100 * (windows_memory_available_bytes{job=\"supercheap_app_windows_server\"})/(3.5 * 1000000000)), 0.01)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(windows_memory_available_bytes{job=\"supercheap_app_windows_server\"}/1000000, 0.01)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "PODs Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU % Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"${namespace}\", pod=~\"${pod}.*\"}[5m])) / sum(kube_pod_container_resource_limits{namespace=\"${namespace}\", resource=\"cpu\", pod=~\"${pod}.*\"})  * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory % Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(max by (pod)(max_over_time(container_memory_usage_bytes{namespace=\"${namespace}\"}[1m]))/ on (pod) (kube_pod_container_resource_limits{namespace=\"${namespace}\", resource=\"memory\", pod=~\"${pod}.*\"}) * 100, 0.01)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(max (max_over_time(container_memory_usage_bytes{namespace=\"${namespace}\", pod=~\"${pod}.*\"}[1m])) / 1000000, 0.01)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}