podSecurityPolicy:
  enabled: true

server:
  persistentVolume:
    enabled: true

prometheus:
  service:
    type: LoadBalancer

  additionalPodMonitors:
    - name: distrans-pod-metrics
      namespaceSelector:
        matchNames:
          - distrans
      selector:
        matchLabels:
          app: distrans
      podMetricsEndpoints:
        - path: /metrics
          port: http

grafana:
  service:
    type: LoadBalancer
